### ISSUE TITLE
Yes, the game does not work outside QWERTY.

### ISSUE THREAD

**Issue by silver-volt4** [CenTdemeern1/HaachamaWare#2]
Leaving this here as an open issue before anyone else comes here and rants about it. We know about it (I do, he does not /s).
Save for the Linux port, the game does not recognize Y/W as the B button.

This will be fixed once there's custom bindings implemented.

**Comment by CenTdemeern1** [comment]
Key rebinding is planned, although you suggested giving it a shot implementing it yourself
I'll leave you to it

**Comment by CenTdemeern1** [comment]
Solved
