### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by MrPowerMac** [CenTdemeern1/HaachamaWare#4]
[According to the GNU Project,](https://www.gnu.org/licenses/license-list.en.html#NoLicense) source code without a license is not free software due to how copyright law works. It looks like the intent is for this project to be FOSS, but until the source code has been explicitly placed under a free software license this is technically a proprietary program.

If you're not sure what license to pick, [choosealicense.com](https://choosealicense.com) is a good place to start.

**Comment by CenTdemeern1** [comment]
I had a certain license in mind, but I kinda forgot to ask the team.
Should have one by the end of today
Good catch, thanks!

**Comment by CenTdemeern1** [comment]
If my computer starts working again, that is.

**Comment by CenTdemeern1** [comment]
Thinking of Creative Commons Attribution_NonCommercial_ShareAlike v4.0 International
Problem is, that only works for the assets
This says nothing about source code
I want something like GPL (but non-commercial?)

**Comment by MrPowerMac** [comment]
The source code being noncommercial would make it non-free software.

> [If a license does not permit users to make copies and sell them, it is a nonfree license.](https://www.gnu.org/philosophy/selling.html)

If you don't want copies of the game as is being sold, then perhaps you could do something similar to the original DOOM: have the source code be free, under GPL, but not the assets (those could be CC-BY-NC-SA or whatever other license you might want). That way the game code itself is still FOSS, but the assets cannot be used commercially.

**Comment by CenTdemeern1** [comment]
Right, someone else suggested that, but that means someone could entirely retexture the game and sell it

**Comment by CenTdemeern1** [comment]
If there is no other option, I might just have to deal with that though 😔

**Comment by CenTdemeern1** [comment]
I assume this can be closed now.
