### ISSUE TITLE
Made using inkscape?

### ISSUE THREAD

**Issue by doctormo** [CenTdemeern1/HaachamaWare#6]
Hi there, I'm adding a few nice looking games to the inkscape website as a showcase and the itch.io page lists inkscape as a tool used to make this game. Is this true? and if so, would it be ok to list on the page: https://inkscape.org/gallery/=games/

**Comment by CenTdemeern1** [comment]
It wasn't much, but part of this game was definitely done using Inkscape!
I did some SVG editing and stuff using Inkscape.

**Comment by CenTdemeern1** [comment]
I would love for it to be shown off on the inkscape website :)

**Comment by CenTdemeern1** [comment]
(I also did some behind the scenes stuff using Inkscape, like figuring out what the settings menu should look like)

**Comment by doctormo** [comment]
Thanks!
